title: [Evaluation of short-read sequencing performance across the Mtb genome]
description: [Genomic sequence characteristics and the empiric accuracy of short-read sequencing (Marin et al. 2021)]

theme: jekyll-theme-cayman